version: "3.3"

volumes:
  static:
  db_data:

services:
  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data/

  web:
    image: niknord/foodgram_backend:latest
    restart: always
    volumes:
      - static:/backend_static
    container_name: web
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: niknord/foodgram_frontend:latest
    volumes:
      - static:/frontend_static
    container_name: frontend
    depends_on:
      - web
    command: cp -r /app/build/. /frontend_static/

  gateway:
    image: niknord/foodgram_gateway:latest
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      - web
