# Generated by Django 4.0 on 2022-12-13 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=4)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Group',
            new_name='Tags',
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-duration']},
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='group',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='recipes',
            name='duration',
            field=models.DurationField(db_index=True, default=datetime.timedelta, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipes/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.ingredients'),
        ),
    ]
