# Generated by Django 4.0 on 2023-02-20 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipes_options_remove_recipes_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='title',
            new_name='name',
        ),
    ]
