# Generated by Django 4.0 on 2023-03-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipes_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipes',
            old_name='ingredient',
            new_name='rel_ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientrecipes',
            old_name='recipe',
            new_name='rel_to_ing_recipe',
        ),
        migrations.RenameField(
            model_name='tagsrecipes',
            old_name='tag',
            new_name='rel_tag',
        ),
        migrations.RenameField(
            model_name='tagsrecipes',
            old_name='recipe',
            new_name='rel_to_tag_recipe',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='recipes_photo/', verbose_name='Photo'),
        ),
    ]
