# Generated by Django 4.0 on 2023-03-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_ingredient_ingredientrecipes_rel_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipes',
            old_name='rel_ingredient',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientrecipes',
            old_name='rel_to_ing_recipe',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='tagsrecipes',
            old_name='rel_to_tag_recipe',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='tagsrecipes',
            old_name='rel_tag',
            new_name='tag',
        ),
    ]
