# Generated by Django 4.0 on 2023-03-19 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_rel_ingredient_ingredientrecipes_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AddField(
            model_name='recipes',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Date created'),
        ),
    ]
