# Generated by Django 4.0 on 2023-03-07 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_recipes_shopping_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='is_favorite',
            field=models.ManyToManyField(blank=True, related_name='is_favorite', to=settings.AUTH_USER_MODEL, verbose_name='is_favorite'),
        ),
    ]
